### ISSUE TITLE
[Bug] 존재하지 않는 page 오류

### ISSUE THREAD

**Issue by Yaminyam** [42-world/42world-Frontend#120]
## 오류 사진 및 설명
#119 issue와 비슷한 문제
존재하지않는 항목에 대한 접근 문제는 비슷하게 발생하는데 해당 이슈는 문제가 될 수 있는 부분이 현재 1~5번 페이지까지 항목이 뜨는데 5번을 눌러보면 실제로 5번페이지가 존재하지 않아 접근이 불가능함 페이지가 존재하는 만큼만 보여줘야 할 것으로 생각됨
<img width="754" alt="image" src="https://user-images.githubusercontent.com/31057849/180604961-9a9ced95-c8b8-4496-bd73-888a09f76b79.png">

## 발생 위치
카테고리 글 목록

**Comment by chichoon** [comment]
문장이 이해가 안되는데 그 맨 밑에 pagination 말씀하시는건가요 ??

**Comment by Yaminyam** [comment]
넵 맞는데 이것도 고쳐진 이슈였던것 같아요! 이슈닫겠습니다 ㅎㅎ

**Comment by chichoon** [comment]
오마네 갑자기 사라져서 놀랏어요 ㅋㅋㅋ

**Comment by Yaminyam** [comment]
@chichoon 정확히는 기억 안나는데 다른것때문에 생겼던 이슈였던것 같아요
