### ISSUE TITLE
[Bug] 피드백 게시판 건의사항 정리

### ISSUE THREAD

**Issue by PIut0** [42-world/42world-Frontend#141]
## 오류 사진 및 설명

- [x] 댓글 좋아요 커서 모양 변경 위치가 하트 아이콘이 아닌 숫자에 있음
https://www.42world.kr/article/488
- [x] 메인화면 텍스트 잘림 현상
https://www.42world.kr/article/458
- [x] 메인 페이지 게시글 미리보기에도 new 생성
https://www.42world.kr/article/596
- [x] 글 목록 아이템 상하 여백 조정
https://www.42world.kr/article/462
- [x] 글 목록 아이템 좋아요 댓글 수 위치 조정
https://www.42world.kr/article/466
- [x] 글쓰기 화면 너비 조정 - 문제 확인 불가능, 추후 다시 확인 필요
https://www.42world.kr/article/584
- [x] 스크롤이 밀릴만한 부분 전부 scroll 삭제 처리
https://www.42world.kr/article/604

- [x] 알람 페이지 CSS 수정
https://www.42world.kr/article/613
https://www.42world.kr/article/607
https://www.42world.kr/article/603
- [x] 광고 배너에 광고 텍스트 빼기

**Comment by Yaminyam** [comment]
앞으로 이슈가 많으면 이슈는 쪼개고 마일스톤이나 프로젝트기능 이용해도 좋을것 같네요!
