### ISSUE TITLE
Tapnav 가로폭 늘릴경우 버그 발생

### ISSUE THREAD

**Issue by Skyrich2000** [42-world/42world-Frontend#17]
모바일이랑 PC 사이의 전환이 너무 부드러워서 정말 CSS의 정수를 보는듯한 기분입니다. 
이것저것 확인해보던중에 오류를 하나 찾아서 이슈 올립니다...

https://user-images.githubusercontent.com/46391729/162827003-45b3fa85-6ac3-43a2-b7b6-18720e39837c.mov

영상보시면, 모바일 환경에서 햄버거를 눌러서 켜놓은상태로 화면을 늘리면 지워지지 않고 남아있더라구요...
솔직히 이렇게까지 해볼사람이 있겠느냐 싶지만 언젠간 수정되면 좋을거같아서 이슈남깁니다

급한 이슈는 아니니까 전체적인 틀 다 잡으시고 하셔도 좋을거같아요 🙂

**Comment by tonyhan18** [comment]
레거시 버전으로 돌리어 일시적으로 해결했습니다. 이후 advanced 버전을 만들어야 겠네요
