### ISSUE TITLE
[Feature] Front-end 폰트 추가

### ISSUE THREAD

**Issue by PIut0** [42-world/42world-Frontend#71]
## 작업할 내용
폰트가 적용되어 있지 않아서 글꼴이 예쁘지 않고,
폰트를 적용하지 않을경우 브라우저 내장 폰트를 사용하게 되는데,
폰트별로 사이즈가 달라서 스타일에 통일성을 주기 어렵습니다.
폰트를 1개 혹은 2개정도 선별해서 전역으로 적용해야 할것 같습니다.

## 해야할 일
- [ ] 폰트 선별
- [ ] 전역으로 폰트 적용

**Comment by rockpell** [comment]
Pretendard랑 Noto Sans 추천합니다
둘중에 하나를 메인으로 선정하면 될거 같네요
둘다 라이센스 문제 없어요

[Pretendard](https://cactus.tistory.com/306)
[Noto Sans](https://fonts.google.com/noto/specimen/Noto+Sans+KR)

**Comment by chichoon** [comment]
[스포카 한 산스](https://spoqa.github.io/spoqa-han-sans/) 도 이쁩니다 [상업적 이용 가능한 오픈소스](https://www.kcopa.or.kr/lay1/program/S1T231C359/copyrightok/contents/view.do?ntt_id=1565)라 마찬가지로 라이선스 괜찮아요 토스 타다 망고플레이트 등에서 사용한다네요
회의때 세개 하나씩 적용해보면서 어울리는걸로 채택해도 좋을것같네요

**Comment by chichoon** [comment]
회의로 Pretendard로 결정 되었습니다
