### ISSUE TITLE
[Feature] 게시판 글 목록에서 좌측 커뮤니티에 데이터 추가

### ISSUE THREAD

**Issue by PIut0** [42-world/42world-Frontend#77]
## 작업할 내용
현재 리팩토링 과정에서 훅이 변경되어서 게시판의 글 목록 페이지의 좌측 커뮤니티 탭 부분이 비어있음.
새로운 훅을 붙여서 데이터 추가

## 해야할 일
카테고리 컴포넌트에 데이터 추가

**Comment by rockpell** [comment]
이거는 search pr머지되면 해결 될 예정입니다

**Comment by PIut0** [comment]
넵! 그럼 미리 close 해두겠습니당
