### ISSUE TITLE
[Bug] 댓글이 많을경우 잘리는 현상

### ISSUE THREAD

**Issue by PIut0** [42-world/42world-Frontend#82]
## 오류 사진 및 설명
<img width="717" alt="image" src="https://user-images.githubusercontent.com/13381535/177553068-6aec9a5f-86ad-4cc1-b4e8-0b6b24aae8b3.png">

댓글이 많을경우 일정 수까지만 보이고 이후 댓글을 볼 수 있는 방법이 없음

**Comment by rockpell** [comment]
#75 랑 같은 내용인거 같습니다
페이지네이션 자체가 적용이 안되어있더라구요

**Comment by PIut0** [comment]
맞네요.. 기존 이슈 제대로 확인하도록 하겠습니다...
