### ISSUE TITLE
[Feature] 알람 스타일 미세 조정

### ISSUE THREAD

**Issue by blingblin-g** [42-world/42world-Frontend#88]
## 해야할 일
- [ ] 모달 창이 안쪽으로 오는 게 자연스러울 것 같습니다. (화면이 잘리는 이슈)
<img width="297" alt="Screen Shot 2022-07-09 at 2 09 13 AM" src="https://user-images.githubusercontent.com/60090391/178038698-195648e4-bd95-4fb9-94d5-1c76408b2915.png">

- [x] styled-component -> emotion으로 교체할 수 있으면 교체
- [x] mui 교체할 수 있으면 교체

**Comment by Skyrich2000** [comment]
@GulSam00 

* 알람 / 알림 이름 통일 해주세요
* 아이콘 크기 고정하고
* 폰트 크기좀 줄여주세요

**Comment by Skyrich2000** [comment]
* 이름이 아니라 알람 아이콘으로 변경

**Comment by chichoon** [comment]
상단바의 알림 버튼이랑 알림 모달이랑 margin으로 간격 넣어주세욤

**Comment by GulSam00** [comment]
![11](https://user-images.githubusercontent.com/72376700/180241930-0fe331bc-affd-4aa0-a560-e84b42ef576e.PNG)
![22](https://user-images.githubusercontent.com/72376700/180241935-9173a258-d6c4-4d0d-9343-9e8e46b30a35.PNG)
리뷰 반영했습니다.
mui를 바닐라 css로 변환하는 과정에서 모달창 위치를 조정해줘야 했는데, left N%로 먹여버릴려다가 반응형 디자인도 고려해야 할 것 같아서 일단은 남겨 놓았습니다.
애니메이션 임시 적용해보았습니다.
