### ISSUE TITLE
[Bug] 댓글 갯수 실시간 변경

### ISSUE THREAD

**Issue by Yaminyam** [42-world/42world-Frontend#95]
## 오류 사진 및 설명
<img width="707" alt="image" src="https://user-images.githubusercontent.com/31057849/179269539-129028e3-269a-4860-a5d9-6cbfcd56c534.png">
댓글창에 있는 댓글 수는 댓글을 달때마다 실시간으로 갯수가 변경이 되고있으나 상단의 게시글 속성의 댓글수는 새로고침을 해야 반영됨

## 발생 위치
게시글

**Comment by chichoon** [comment]
그러네요 이거 좀 킹받네요 상태관리 추가해야할거같네요
