### ISSUE TITLE
[Bug] 삭제버튼 잘못된 활성화

### ISSUE THREAD

**Issue by Yaminyam** [42-world/42world-Frontend#96]
## 오류 사진 및 설명
<img width="512" alt="image" src="https://user-images.githubusercontent.com/31057849/179270264-dbc39e92-61a6-446a-afb0-14babe91a93e.png">
본인의 댓글에 삭제버튼이 생겨야하는데 게시글 작성자의 댓글에 삭제버튼이 보임

## 발생 위치
게시글 댓글창

**Comment by chichoon** [comment]
허ㅓ억

**Comment by Skyrich2000** [comment]
수정완료!
